### ISSUE TITLE
Virtual Console issues while Plugin Loader is enabled.

### ISSUE THREAD

**Issue by MrGringo418** [cooolgamorg/Starlight3DS#16]
Here's a very strange bug I've encountered:

If I have the "enable plugin loader" option enabled, while playing certain Virtual Console titles, the screens flash purple and then stay black, with buttons being unresponsive. (If Rosalina is configured to use the HOME menu, it opens just fine. So it's not a complete freeze)

The Virtual Console games seem _**VERY**_ specific.

- Game Gear doesn't crash
- All NES VC titles crash
- Wario Land 4 (Ambassador GBA) crashes
- Pokémon Fire Red (Injected GBA) doesn't crash
- Pokémon Red (GB, from eShop) crashes
- Pokemon Mew Trading ("legit" leaked event cxi) crashes
- Shantae (GBC eShop) crashes
- Shantae GBA enhanced (inject of the patched rom) doesn't crash
- Pokémon Gold (GBC eShop) crashes
- Pokémon Crystal (GBC eShop) doesn't crash

I've tried multiple resolutions

- Disable Clock+L2
- Disable Wumiibo

The only thing that works is to disable plugins, which created another issue...

If I want to play certain VC games, I have to disable Pretendo (as it requires game patching). This seems to log me out of my Pretendo account and I have to re-link Pretendo every time I want to go online

**Comment by cooolgamer** [comment]
This isn't a Starlight3DS or Luma3DS issue, but a CTRPF issue... I tried reporting it multiple times on some Discord servers but I get ignored... This isn't the right place
