### ISSUE TITLE
Donkey Kong Country Returns 3D

### ISSUE THREAD

**Issue by BloodSlayer3DS** [cooolgamorg/Starlight3DS#17]
Donkey Kong Country Returns 3D doesn't work while using Starlight3DS. I have no idea why.

**Comment by cooolgamer** [comment]
can you be more specific? That doesn't really help, I don't have this game.

**Comment by BloodSlayer3DS** [comment]
With StarLight3DS active, DKCR gets stuck on the first loading screen before the main menu.

**Comment by cooolgamer** [comment]
I geniuenly have no clue why this happens, I'm not really an expert when it comes to this sort of stuff...

**Comment by BloodSlayer3DS** [comment]
That's fine. I appreciate you at least trying.

**Comment by patrickwinslow** [comment]
It runs normally with the latest Luma.

**Comment by patrickwinslow** [comment]
> OK that's something. 
> Did you tried disabling the plugin loader and then boot the game?
> Obviously using this luma version 

I don't have Starlight3DS installed right now. I'll try it soon.

**Comment by BloodSlayer3DS** [comment]
> > It runs normally with the latest Luma.
> 
> OK that's something. 
> Did you tried disabling the plugin loader and then boot the game?
> Obviously using this luma version 

Even without the plugin loader, it doesn't run. It's been so long since I've used Starlight, so I'll try this regardless today, and let you know.

**Comment by patrickwinslow** [comment]
The game seems to work fine with the latest release, even with the plugin loader enabled (although I have no plugins). Maybe it was a regression in upstream Luma which was fixed?

**Comment by BloodSlayer3DS** [comment]
I was trying to get Starlight again but it's been taken off Universal Updater, so, I'm glad! I'll try to fine a lazy way to get Starlight again though cause I forgot how to manually change that bit of the 3DS.

**Comment by cooolgamer** [comment]
So it was a official luma issue that got fixed by updating it, then I can close it
