### ISSUE TITLE
Starlight 3DS Configuration issue

### ISSUE THREAD

**Issue by BloodSlayer3DS** [cooolgamorg/Starlight3DS#20]
For some reason, whenever I, for example, change to Pretendo severs, the configuration menu shows up, reset. Meaning, shows up without any of my previous selections selected. No idea what's going on. I tried switching from Luma back to Starlight, but no fix. The way I'm getting Starlight on my 3DS (Due to it being gone from Universal Updater for some reason), is by replacing the Luma boot.firm with Starlight's boot.firm.

**Comment by BloodSlayer3DS** [comment]
For some reason, the issue had to do with Miiverse error code 015-5015, which is me being signed out from my Pretendo acc. I logged back in, and all was well.

**Comment by BloodSlayer3DS** [comment]
This issue is actually still happening. It's just whenever I power on the 3DS now.

**Comment by BloodSlayer3DS** [comment]
I'm giving you as much details as I possibly can. Can you be clear on what you wish to know? I don't know what else to mention.

**Comment by BloodSlayer3DS** [comment]
Finally figured out why this issue happens. For some reason, when the splash is set to before or after payloads, it causes this. No idea why it does this, but it does. So, no more using splash screen for me ig.

**Comment by BloodSlayer3DS** [comment]
https://photos.app.goo.gl/utVCJP9PoLLQcVBN8

**Comment by cooolgamer** [comment]
I can't reproduce it, make sure you're using the latest version of Starlight3DS, v1.6.2 is the latest

**Comment by BloodSlayer3DS** [comment]
> I can't reproduce it, make sure you're using the latest version of Starlight3DS, v1.6.2 is the latest
> Also, delete luma/configplus.ini and try again

Just configplus.ini, not the entire Luma file right?

**Comment by BloodSlayer3DS** [comment]
@cooolgamer I did as exactly as you said and it's still happening.

**Comment by cooolgamer** [comment]
I have no idea then 🤔

**Comment by BloodSlayer3DS** [comment]
Unfortunately, I cannot. Sorry.

**Comment by BloodSlayer3DS** [comment]
Did you not get the video?> > @cooolgamer I did as exactly as you said and it's still happening.
> > 
> > Updated to the latest version btw
> 
> @BloodSlayer3DS can you join the discord that way you can send a video and let us see if you don't mind?
> https://discord.gg/2PEFjuSd

**Comment by BloodSlayer3DS** [comment]
I just started to have the issue again. I was using "Start" to save the changes made (putting the things back the way they were as before) and exiting to the Home Menu.

It did it again.

I made my changes again and this time, went down to "Save and Exit" and pressed it.

The issue no longer happened.

🤷🏽‍♂️
