### ISSUE TITLE
*ADDING FEATURE* plugin selector.

### ISSUE THREAD

**Issue by gvvq** [cooolgamorg/Starlight3DS#8]
adding the possibility to select plugins to load in the game. kinda like the cheat section. BUT without having to remove them from ur sd card

**Comment by Billyfury31** [comment]
I have already passed the source of a plugin selector to the owner of the repository. You just need to wait for them to add it. In the meantime, you can check out my fork where I have already added this feature ^^

**Comment by gvvq** [comment]
@Billyfury31 that exactly why i asked this feature to be apart of the base starlight3ds. since i took a look at yours. but it would be better if it was included!

**Comment by Billyfury31** [comment]
I haven't added any additional features. On the one hand, I created this fork not long ago, so I don't know what to include. Additionally, I don't consider myself experienced enough to contribute to Starlight3DS. "My" plugin loader is a copy and paste of the plugin loader from this guy's, with just a few minor modifications to adapt it for use with Starlight. However, if I have any ideas in the future, I will try to add them and contribute to the project! ^^

**Comment by gvvq** [comment]
i still appreciate the work! but honestly add anything that u think can be cool! like other setting. or even QoL likes more thing that look like "gimmie 300 coins" !

**Comment by gvvq** [comment]
Another feature that would be cool adding! MCU bricker! (changing the led notifications to rgb) would be fun to do so from starlight3ds menu!

**Comment by cooolgamer** [comment]
I'll check the plugin selector feature, the issue with this is that it doesn't include only this but also other features that may be unwanted, I avoid using PRs because that would credit someone who didn't make the feature :/

**Comment by gvvq** [comment]
:)

**Comment by cooolgamer** [comment]
Added in [this commit](https://github.com/cooolgamorg/Starlight3DS/commit/2aef8d3d2b5fdf4962743897bd061de465536640)
