### ISSUE TITLE
Make StarLight3DS compatible with CTGP-7

### ISSUE THREAD

**Issue by gvvq** [cooolgamorg/Starlight3DS#9]
Make starLight3ds compatible with CTGP-7! would be great!
![2024-05-26_22-12-01 273_top](https://github.com/cooolgamorg/Starlight3DS/assets/135171695/b71fed4a-ada2-4b93-ad82-2092731ec2d9)

**Comment by bitten2up** [comment]
> This is not possible because of their anti-cheat system.

sorry but would you be interested in a work around so then it doesn't get overwritten by accident?

**Comment by cooolgamer** [comment]
I guess I can ask PabloMK7 to allow this build but I'm not sure about that...

And to not overwrite it, just cancel, you can't really "accidentally" replace it. And if it happens, just put Starlight3DS again

**Comment by bitten2up** [comment]
> I guess I can ask PabloMK7 to allow this build but I'm not sure about that...
> 
> And to not overwrite it, just cancel, you can't really "accidentally" replace it. And if it happens, just put Starlight3DS again

personally i'm in the habbit of pressing a, currently i have a build that redirects it to a different file for personal reasons, thats why i was asking

**Comment by OasisVee** [comment]
A workaround I use is move Luma's boot.firm to /luma/payloads then add a button shortcut to its name so that when I want to play CTGP-7 I can just power off and then hold that button and power
